# Generated by Django 4.2.2 on 2023-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
