# Generated by Django 4.2.2 on 2023-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("additional_info", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
