# Generated by Django 4.2.2 on 2023-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
